export const wikiCategories = [
  {
    label: "Bosses",
    href: "/gods-blessings",
    iconSrc: "/images/wiki-icons/bosses.png",
    iconAlt: "Guardian of Minerva's Nest icon from Romestead",
    description: "Prepare food, gear, blessings, and a safe return plan before pushing a major fight.",
  },
  {
    label: "Enemies",
    href: "/beginner-guide",
    iconSrc: "/images/wiki-icons/enemies.png",
    iconAlt: "Bone icon from Romestead",
    description: "Learn when to defend, when to retreat, and how to avoid losing a run to night pressure.",
  },
  {
    label: "Gods",
    href: "/gods-blessings",
    iconSrc: "/images/wiki-icons/gods.png",
    iconAlt: "Minerva ghost icon from Romestead",
    description: "Choose blessings around your current problem: food, defense, crafting, or exploration.",
  },
  {
    label: "Quests",
    href: "/beginner-guide",
    iconSrc: "/images/wiki-icons/quests.png",
    iconAlt: "Scroll of Vulcan icon from Romestead",
    description: "Use objectives to set your next task instead of wandering too far from the settlement.",
  },
  {
    label: "Biomes",
    href: "/beginner-guide",
    iconSrc: "/images/wiki-icons/biomes.png",
    iconAlt: "Plains biome icon from Romestead",
    description: "Scout nearby areas first, then expand once food, storage, and defense can support trips.",
  },
  {
    label: "Skills",
    href: "/is-it-worth-it",
    iconSrc: "/images/wiki-icons/skills.png",
    iconAlt: "Unarmed skill icon from Romestead",
    description: "Decide whether your build should solve combat, gathering, crafting, or town upkeep.",
  },
  {
    label: "Weapons",
    href: "/gods-blessings",
    iconSrc: "/images/wiki-icons/weapons.png",
    iconAlt: "Arsenal icon from Romestead",
    description: "Match weapons with the fight you are taking and the supplies your town can replace.",
  },
  {
    label: "Tools",
    href: "/base-building",
    iconSrc: "/images/wiki-icons/tools.png",
    iconAlt: "Construction skill icon from Romestead",
    description: "Upgrade tools around the materials blocking your next workstation or base expansion.",
  },
  {
    label: "Trinkets",
    href: "/gods-blessings",
    iconSrc: "/images/wiki-icons/trinkets.png",
    iconAlt: "Fascinus trinket icon from Romestead",
    description: "Use trinkets to support the job you are doing now: fighting, farming, or exploring.",
  },
  {
    label: "Armor",
    href: "/beginner-guide",
    iconSrc: "/images/wiki-icons/armor.png",
    iconAlt: "Armory icon from Romestead",
    description: "Improve survival before longer trips, boss attempts, or risky night defense.",
  },
  {
    label: "Resources",
    href: "/farming",
    iconSrc: "/images/wiki-icons/resources.png",
    iconAlt: "Lumber resource icon from Romestead",
    description: "Find which materials to gather first and where to store them so crafting stays fast.",
  },
  {
    label: "Crafting",
    href: "/base-building",
    iconSrc: "/images/wiki-icons/crafting.png",
    iconAlt: "Crafting icon from Romestead",
    description: "Build the workstation chain that unlocks better tools, storage, food, and defense.",
  },
];
